# Copyright 2025 ox-warrior
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This rule is not used by the project floz itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to floz.io.floz.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: floz
    app.kubernetes.io/managed-by: kustomize
  name: grouppolicies-viewer-role
rules:
- apiGroups:
  - floz.io.floz.io
  resources:
  - grouppolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - floz.io.floz.io
  resources:
  - grouppolicies/status
  verbs:
  - get
